services:
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: guitar_store
      POSTGRES_USER: dmitrii
      POSTGRES_PASSWORD: bonch2024
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
